apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "install.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "install.labels" . | nindent 4 }}
